In [1]:
import numpy as np

In [5]:
np.random.seed(101)

arr = np.random.randint(0,100,10)

In [11]:
arr.max()

95

In [12]:
arr.argmax()

0

In [24]:
mat = np.arange(1,101).reshape((10,10))

In [25]:
mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [22]:
mat.shape

(10, 10)

In [26]:
mat[3,2]

33

In [27]:
mat[6,4]

65

In [28]:
mat[5,3]

54

In [34]:
mat[:,1].shape

(10,)

In [36]:
mat[:,1].reshape(10,1)

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [39]:
mat[0:7,0:2] = 0

In [40]:
mat

array([[  0,   0,   3,   4,   5,   6,   7,   8,   9,  10],
       [  0,   0,  13,  14,  15,  16,  17,  18,  19,  20],
       [  0,   0,  23,  24,  25,  26,  27,  28,  29,  30],
       [  0,   0,  33,  34,  35,  36,  37,  38,  39,  40],
       [  0,   0,  43,  44,  45,  46,  47,  48,  49,  50],
       [  0,   0,  53,  54,  55,  56,  57,  58,  59,  60],
       [  0,   0,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [41]:
new_mat = mat.copy()

In [43]:
mat[:,5] =0

In [44]:
mat

array([[  0,   0,   3,   4,   5,   0,   7,   8,   9,  10],
       [  0,   0,  13,  14,  15,   0,  17,  18,  19,  20],
       [  0,   0,  23,  24,  25,   0,  27,  28,  29,  30],
       [  0,   0,  33,  34,  35,   0,  37,  38,  39,  40],
       [  0,   0,  43,  44,  45,   0,  47,  48,  49,  50],
       [  0,   0,  53,  54,  55,   0,  57,  58,  59,  60],
       [  0,   0,  63,  64,  65,   0,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,   0,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,   0,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,   0,  97,  98,  99, 100]])

In [45]:
new_mat

array([[  0,   0,   3,   4,   5,   6,   7,   8,   9,  10],
       [  0,   0,  13,  14,  15,  16,  17,  18,  19,  20],
       [  0,   0,  23,  24,  25,  26,  27,  28,  29,  30],
       [  0,   0,  33,  34,  35,  36,  37,  38,  39,  40],
       [  0,   0,  43,  44,  45,  46,  47,  48,  49,  50],
       [  0,   0,  53,  54,  55,  56,  57,  58,  59,  60],
       [  0,   0,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [46]:
mat[0:6,:] = 999

In [47]:
mat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [  0,   0,  63,  64,  65,   0,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,   0,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,   0,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,   0,  97,  98,  99, 100]])

In [30]:
mat[1,:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])